name: wordbook # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.3.1' # just for humans, typically '1.2+git' or '1.3.2'
adopt-info: wordbook
license: GPL-3.0
issues: https://github.com/soumyaDghosh/wordbook-snap/issues
source-code: https://github.com/mufeedali/Wordbook
website: https://github.com/soumyaDghosh/wordbook-snap
compression: lzo
icon: com.github.fushinari.Wordbook.svg
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
title: Wordbook
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
layouts:
  /usr/lib/x86_64-linux-gnu/espeak-ng-data:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/espeak-ng-data
parts:
  pcaudiolib:
    plugin: autotools
    source: https://github.com/espeak-ng/pcaudiolib.git
    source-tag: 1.2
    autotools-configure-parameters:
      - --prefix=/usr
  wordbook:
    after: [ pcaudiolib ]
    # See 'snapcraft plugins'
    plugin: meson
    source: https://github.com/mufeedali/Wordbook.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    meson-parameters:
      - --prefix=/snap/wordbook/current/usr
    organize:
      snap/wordbook/current: .
    stage-packages:
      - espeak-ng-espeak
      - espeak-ng-data
    override-build: |
      craftctl default
      pip install --target=$CRAFT_PART_INSTALL/snap/wordbook/current/usr/lib/python3/dist-packages wn==0.6.1
      sed -e '1c#!/usr/bin/env python3' -i "${CRAFT_PART_INSTALL}/snap/wordbook/current/usr/bin/wordbook"
    parse-info: [ usr/share/appdata/com.github.fushinari.Wordbook.appdata.xml ]
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - wordbook
      - pcaudiolib
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core22
      - gtk-common-themes
      - gnome-42-2204
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do  # List all content-snaps and base snaps you're using here
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
slots:
  wordbook:
    interface: dbus
    bus: session
    name: com.github.fushinari.Wordbook
apps:
  wordbook:
    command: usr/bin/wordbook
    desktop: usr/share/applications/com.github.fushinari.Wordbook.desktop
    common-id: com.github.fushinari.Wordbook
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
    extensions: [ gnome ]
    plugs:
      - alsa
      - audio-playback
      - network
      - network-observe
      - network-status
