name: wordbook # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.3.1' # just for humans, typically '1.2+git' or '1.3.2'
adopt-info: wordbook
license: GPL-3.0
issues: https://github.com/soumyaDghosh/wordbook-snap/issues
source-code: https://github.com/mufeedali/Wordbook
website: https://github.com/soumyaDghosh/wordbook-snap
compression: lzo
icon: com.github.fushinari.Wordbook.svg
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
title: Wordbook
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
parts:
  wordbook:
    # See 'snapcraft plugins'
    plugin: meson
    source: https://github.com/mufeedali/Wordbook.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    meson-parameters:
      - --prefix=/snap/wordbook/current/usr
    organize:
      snap/wordbook/current: .
    stage-packages:
      - espeak-ng-espeak
    override-build: |
      craftctl default
      pip install --target=$CRAFT_PART_INSTALL/snap/wordbook/current/usr/lib/python3/dist-packages wn==0.6.1
      sed -e '1c#!/usr/bin/env python3' -i "${CRAFT_PART_INSTALL}/snap/wordbook/current/usr/bin/wordbook"
    parse-info: [ usr/share/appdata/com.github.fushinari.Wordbook.appdata.xml ]
    
slots:
  wordbook:
    interface: dbus
    bus: session
    name: com.github.fushinari.Wordbook
apps:
  wordbook:
    command: usr/bin/wordbook
    desktop: usr/share/applications/com.github.fushinari.Wordbook.desktop
    common-id: com.github.fushinari.Wordbook
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
    extensions: [ gnome ]
    plugs:
      - audio-playback
      - network
      - network-observe
      - network-status
